gpu_id: '0'
log_wandb: False

# EchoMamba4Rec settings
hidden_size: 64
num_layers: 2
dropout_prob: 0.2
loss_type: 'CE'

d_state: 32
d_conv: 4
expand: 2
initializer_range : 0.02
num_experts : 2
num_heads : 8

# dataset settings
#dataset: ml-1m
#MAX_ITEM_LIST_LENGTH: 200

dataset: ml-32m
MAX_ITEM_LIST_LENGTH: 200

#dataset: gowalla-m
#MAX_ITEM_LIST_LENGTH: 100
#
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
load_col:
    inter: [user_id, item_id, timestamp]

user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"

# Netflix dateset
#dataset: netflix
#MAX_ITEM_LIST_LENGTH: 200
#USER_ID_FIELD: user_id
#ITEM_ID_FIELD: item_id
#load_col:
#    inter: [item_id, user_id, timestamp]
#
#user_inter_num_interval: "[50,inf)"
#item_inter_num_interval: "[50,15000]"


# LFM1b-Artists dateset
#dataset: lfm1b-artists
#MAX_ITEM_LIST_LENGTH: 200
#
#USER_ID_FIELD: user_id
#ITEM_ID_FIELD: artists_id
#load_col:
#    inter: [user_id, artists_id, timestamp]
#
#user_inter_num_interval: "[5,500]"
#item_inter_num_interval: "[5,inf)"

# training settings
epochs: 300
train_batch_size: 2048
learner: adam
learning_rate: 0.001
eval_step: 1
stopping_step: 20
train_neg_sample_args: ~

# evalution settings
metrics: ['Hit', 'NDCG', 'MRR']
valid_metric: NDCG@10
eval_batch_size: 4096
weight_decay: 0.0
topk: [10, 20]






